apiVersion: v1
kind: Pod
metadata:
  name: webapp-with-config
  labels:
    app: webapp-config
spec:
  containers:
  - name: webapp
    image: nginx:latest
    env:
    - name: ENV
      valueFrom:
        configMapKeyRef:
          name: webapp-config
          key: ENV
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: webapp-secret
          key: PASSWORD
    - name: CONFIG_FILE
      value: "/etc/config/app.properties"
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
    - name: secret-volume
      mountPath: /etc/secrets
      readOnly: true
  volumes:
  - name: config-volume
    configMap:
      name: webapp-config
  - name: secret-volume
    secret:
      secretName: webapp-secret